version: 2
updates:
- package-ecosystem: npm
  directory: "/{{cookiecutter.project_slug}}"
  schedule:
    interval: weekly
    day: sunday
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-native-screens
    versions:
    - 1.0.0-alpha.23
    - 3.0.0
    - 3.1.0
  - dependency-name: react-native-elements
    versions:
    - 3.3.2
  - dependency-name: react-native-dotenv
    versions:
    - 2.5.1
    - 2.5.3
  - dependency-name: metro-react-native-babel-preset
    versions:
    - 0.65.0
    - 0.65.1
    - 0.65.2
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
  - dependency-name: react-native-image-picker
    versions:
    - 3.1.4
    - 3.2.1
    - 3.3.2
  - dependency-name: react-native-reanimated
    versions:
    - 1.13.2
    - 1.13.3
  - dependency-name: babel-jest
    versions:
    - 26.6.3
