export const CALENDAR_GOOGLE_LOGIN_REQUEST = "CALENDAR/GOOGLE_LOGIN/REQUEST";
export const CALENDAR_GOOGLE_LOGIN_SUCCESS = "CALENDAR/GOOGLE_LOGIN/SUCCESS";
export const CALENDAR_GOOGLE_LOGIN_ERROR = "CALENDAR/GOOGLE_LOGIN/ERROR";

export const CALENDAR_DATA_REQUEST = "CALENDAR/DATA/REQUEST";
export const CALENDAR_DATA_SUCCESS = "CALENDAR/DATA/SUCCESS";
export const CALENDAR_DATA_ERROR = "CALENDAR/DATA/ERROR";
