export const EMAIL_AUTH_SIGNUP_REQUEST = "EMAIL_AUTH/SIGNUP/REQUEST";
export const EMAIL_AUTH_SIGNUP_SUCCESS = "EMAIL_AUTH/SIGNUP/SUCCESS";
export const EMAIL_AUTH_SIGNUP_ERROR = "EMAIL_AUTH/SIGNUP/ERROR";

export const EMAIL_AUTH_LOGIN_REQUEST = "EMAIL_AUTH/LOGIN/REQUEST";
export const EMAIL_AUTH_LOGIN_SUCCESS = "EMAIL_AUTH/LOGIN/SUCCESS";
export const EMAIL_AUTH_LOGIN_ERROR = "EMAIL_AUTH/LOGIN/ERROR";

export const EMAIL_AUTH_PASSORD_RECOVER_REQUEST =
  "EMAIL_AUTH/PASSORD_RECOVER/REQUEST";
export const EMAIL_AUTH_PASSORD_RECOVER_SUCCESS =
  "EMAIL_AUTH/PASSORD_RECOVER/SUCCESS";
export const EMAIL_AUTH_PASSORD_RECOVER_ERROR =
  "EMAIL_AUTH/PASSORD_RECOVER/ERROR";
