# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

opt_out_usage

default_platform(:ios)

app_name = "testci"
base_name = "testci"
team_name = "Crowdbotics Corporation"
team_id = "6YKR59QXKM"
filename = "#{base_name}.xcodeproj"
workspaceName = "#{base_name}.xcworkspace"
identifier = "com.crowdbotics.#{app_name}"

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :tests do
    run_tests(workspace: workspaceName, scheme: base_name, build_for_testing: true)
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do

    produce(
      app_identifier: identifier,
      app_name: app_name,
      team_name: team_name,
      itc_team_name: team_name
    )
    increment_build_number(xcodeproj: filename)
    update_app_identifier(
      xcodeproj: filename,
      plist_path: "#{base_name}/Info.plist",
      app_identifier: identifier
    )
    update_project_team(path: filename, teamid: team_id)
    match(type: "appstore", readonly: is_ci)
    disable_automatic_code_signing(
      path: filename,
      code_sign_identity: "iPhone Distribution: #{team_name} (#{team_id})"
    )
    settings_to_override = {
      BUNDLE_IDENTIFIER: identifier,
      PROVISIONING_PROFILE_SPECIFIER: "match AppStore #{identifier}"
    }
    build_app(
      scheme: base_name,
      export_method: "app-store",
      xcargs: settings_to_override,
    )
    upload_to_testflight(
      email: "",
      beta_app_description: "Beta version of #{app_name} uploaded by Crowdbotics"
    )
  end
end
