# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '{{cookiecutter.project_slug}}' do

  # Pods for {{cookiecutter.project_slug}}
  # Base dependencies, don't modify this unless you know what you are doing
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Add aditional dependencies here
  
  {% if cookiecutter.has_maps_blueprint == "y" %}
  # react-native-maps dependencies
  pod 'react-native-maps', path: '../node_modules/react-native-maps'
  pod 'react-native-google-maps', '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  {% endif %}

end

post_install do |installer|
  installer.pods_project.targets.each do |target|

    # Add your custom iterators here

    {% if cookiecutter.has_maps_blueprint == "y" %}
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    {% endif %}

    if target.name == "React"
      target.remove_from_project
    end
  end
end
