# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs all the tests"
  lane :tests do
    run_tests(project: "mobile_Myapp.xcodeproj", scheme: "mobile_Myapp")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "mobile_Myapp.xcodeproj")
    match(type: "appstore", readonly: is_ci)
    build_app(scheme: "mobile_Myapp")
    upload_to_testflight
  end
end
