name: build-deploy

on:
  push:
    branches:
      - develop
      - qa
      - staging
    tags:
      - "[0-9]+.[0-9]+"

jobs:
  set_environment:
    outputs:
      environment: ${{ steps.setenv.outputs.my_env }}
      backend: ${{ steps.setenv.outputs.cb_backend }}
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment
        id: setenv
        uses: crowdbotics/github-actions/set-environment@master

  release:
    runs-on: ubuntu-latest
    needs: set_environment
    environment:
      name: ${{ needs.set_environment.outputs.environment }}
    name: ${{ needs.set_environment.outputs.environment }}-release
    steps:
      - name: Generate Heroku Config
        run: |
          cat <<EOF > ~/.netrc 
          machine api.heroku.com
            login ${{ secrets.HEROKU_EMAIL }}
            password ${{ secrets.HEROKU_API_TOKEN }}
          machine git.heroku.com
            login  ${{ secrets.HEROKU_EMAIL }}
            password ${{ secrets.HEROKU_API_TOKEN }}
          EOF
      - name: release scaffold
        run: |
          heroku config:set REACT_NATIVE_SCAFFOLD_REPO_BRANCH=$GITHUB_REF_NAME -a ${{ secrets.HEROKU_APP }}
